language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install: "pip install -r requirements.txt && pip install -r requirements-dev.txt"
# command to run tests
script: PYTHONPATH=$PWD make test
